CREATE TABLE dbo.SKU (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Code AS 's' + CAST(ID AS VARCHAR(10)),
    Name VARCHAR(255) NOT NULL,
    CONSTRAINT UQ_SKU_Code UNIQUE (Code)
);

CREATE TABLE dbo.Family (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SurName VARCHAR(255) NOT NULL,
    BudgetValue DECIMAL(18, 2) DEFAULT 0
);

CREATE TABLE dbo.Basket (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_SKU INT NOT NULL,
    ID_Family INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity >= 0),
    Value DECIMAL(18, 2) NOT NULL CHECK (Value >= 0),
    PurchaseDate DATE DEFAULT GETDATE(),
    DiscountValue DECIMAL(18, 2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_Basket_SKU FOREIGN KEY (ID_SKU) REFERENCES dbo.SKU(ID),
    CONSTRAINT FK_Basket_Family FOREIGN KEY (ID_Family) REFERENCES dbo.Family(ID)
);